### ISSUE TITLE
No unicode typing

### ISSUE THREAD

**Issue by DeexCoding** [Zarzelcow/legacy-lwjgl3#1]
Original Minecraft 1.8.9 supports typing in chat with unicode characters, but with legacy-lwjgl3 this feature is not working properly.

Its especially weird, because getEventCharacter returns a char, which is a byte, which only supports ASCII charcters, so I don't even know how Minecraft managed to do it in the first place.

By the way I love the work you are doing and I find it very helpful to use it as a template in my own project!

**Comment by Zarzelcow** [comment]
oh! thanks for the issue, sorry for the late reply found out GitHub was only sending notifications to my email so I missed the issue while checking my homepage.

on the topic of the issue though, the problem you describe is most likely because of the `getCharacter` function in `Keyboard.kt` using a hard coded list of keycodes to characters (relic of the original Forge mod by gudenau).

I have replaced this with a solution using the glfw character callback instead of the old `getCharacter` function meaning it will use os reported chars instead.

I'm not 100% sure on this fix however as I was not sure as to what 'Unicode typing' meant my guess is that it was a key not in the list of keys ported over from lwjgl2 (maybe something like GLFW_KEY_WORLD_1).

anyways if you find this is still an issue let me know I'll try my best to help.
P.S Didn't mean to make GitHub close this automatically

**Comment by DeexCoding** [comment]
By unicode typing I meant typing non-ASCII characters in the chat. I haven't tested in like... command blocks, but I imageine the issue still would persist.
I'll check out the fix in a bit.

**Comment by DeexCoding** [comment]
The unicode characters work now, but now the backspace repeat events are broken. I can't hold down backspace to delete the entire message, I have to spam it.

**Comment by Zarzelcow** [comment]
That was completely my fault I accidentally left in `action != GLFW_REPEAT` from debugging without realizing it, my bad

**Comment by Zarzelcow** [comment]
forgot to mention I did in fact revert the single line of code that caused the repeat event issue

**Comment by DeexCoding** [comment]
I tested it a little and it seems to work.
